//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_JYR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PedidoDetalle
    {
        public int Id { get; set; }
        [Display(Name = "Pedido")]
        public int IdPedido { get; set; }
        [Display(Name = "Producto")]
        public int IdProducto { get; set; }
        public double Cantidad { get; set; }
        [Display(Name = "Precio Unitario")]
        public double PrecioUnitario { get; set; }
        public double Descuento { get; set; }
        [Display(Name = "Cantidad Enviada")]
        public Nullable<double> CantidadEnviada { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
