//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_JYR.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
        }

        public int Id { get; set; }

        [System.ComponentModel.DisplayName("Usuario")]
        public string IdUsuario { get; set; }
        [System.ComponentModel.DisplayName("Estado")]
        public int IdEstado { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }

        [System.ComponentModel.DisplayName("Total Pagar")]
        public double TotalPagar { get; set; }
        [System.ComponentModel.DisplayName("Total Descuento")]
        public double TotalDescuento { get; set; }
        [System.ComponentModel.DisplayName("Total Impuesto")]
        public double TotalImpuesto { get; set; }
        [System.ComponentModel.DisplayName("Número Proforma")]
        public Nullable<int> NumeroProforma { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
    }
}
